steps:
  - name: gcr.io/cloud-builders/kubectl
    id: test  
    args:
      - '-c'
      - |
        echo "test1" 
        set -ex
        if ! curl -sSL "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64" -o argocd; then
        echo "Error: Download Argocd failed"
          exit 1
        fi
        chmod +x argocd

        mv argocd /usr/local/bin/ # Loại bỏ sudo



        if ! gcloud container clusters get-credentials test-estimate-tera --zone
        asia-southeast1-a --project prj-vn-int-sa-north-lab; then
          echo "Error: Failed to get Kubernetes credentials."
          exit 1
        fi




        if ! /usr/local/bin/argocd login "${_ARGOCD_SERVER}"
        --username="${_ARGOCD_USERNAME}" --password="${_ARGOCD_PASSWORD}"
        --insecure; then
          echo "Error: ArgoCD login failed."
          exit 1
        fi



        /usr/local/bin/argocd app list -o name | while read app; do
          echo "Syncing application: $app"
          if ! /usr/local/bin/argocd app sync "$app"; then
            echo "Error: Failed to sync application $app."
            # Consider whether to continue or exit on failure.  `exit 1` will stop the entire process.
            # exit 1
          fi
        done
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
