steps:
  - name: gcr.io/cloud-builders/kubectl
    args:
      - '-c'
      - |
        echo "test1" 
        set -ex
        if ! curl -sSL "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64" -o argocd; then
        echo "Error: Download Argocd failed"
          exit 1
        fi
        chmod +x argocd

        mv argocd /usr/local/bin/ # 

        if ! gcloud container clusters get-credentials test-estimate-tera --zone asia-southeast1-a --project prj-vn-int-sa-north-lab; then
          echo "Error: Failed to get Kubernetes credentials."
          exit 1
        fi
        kubectl scale deployments --all --replicas=1 -n argocd
        sleep 100
        if ! /usr/local/bin/argocd login "${_ARGOCD_SERVER}" --username="${_ARGOCD_USERNAME}" --password="${_ARGOCD_PASSWORD}" --insecure; then
          echo "Error: ArgoCD login failed."
          exit 1
        fi

        /usr/local/bin/argocd  argocd app list -o name | xargs -I {} argocd app sync {}
        done
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
